services:
  backend:
    build:
      context: ./finance_dashboard_backend
    env_file:
      - ./finance_dashboard_backend/.env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://neelpatel3:Harshida0615!@finance-dashboard-db.cheg2i2wk0rl.us-east-2.rds.amazonaws.com:5432/postgres
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "finance_dashboard_backend.wsgi:application", "--workers", "3", "--timeout", "120"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network


  frontend:
    build:
      context: ./finance-dashboard
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network
    

networks:
  app-network:

volumes:
  postgres_data: