# Generated by Django 5.1 on 2024-08-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='current_amount',
            new_name='currentAmount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='target_amount',
            new_name='targetAmount',
        ),
    ]
