name: CI/CD Pipeline

on:
  push:
    branches:
      - last-try
  pull_request:
    branches:
      - last-try

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./finance_dashboard_backend

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./finance-dashboard

      - name: Build Angular project
        run: npm run build -- --configuration=finance-dashboard
        working-directory: ./finance-dashboard
      
      - name: Collect Django static files
        run: python manage.py collectstatic --noinput
        working-directory: ./finance_dashboard_backend

      - name: Apply Django migrations
        run: python manage.py migrate
        working-directory: ./finance_dashboard_backend

      - name: Set up Python for EB CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli
      
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          eb init -p python-3.9 fin --region us-east-1
          eb use Fin-env

      - name: List build directory contents for debugging
        run: |
          ls -al ./finance-dashboard/dist/
          ls -al ./finance-dashboard/dist/finance-dashboard/
        
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./finance-dashboard/dist/finance-dashboard s3://my-angular-bucket-dashboard --delete --region us-east-1

